#!/usr/bin/env bash
# installs Nginx on my server
#+ listens on port 80
#+  return a page that contains the string Hello World!
#++ When querying Nginx at its root / with a GET request
sudo apt-get update -y
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
