#!/usr/bin/bash
# Install and configure HAproxy on server
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get install haproxy=2.0.\*

# edit config file
server_config=\
"
frontend nuel07
        bind *:80
        mode http
        default_backend nuel07
backend nuel07
        balance roundrobin
        server 380-web-01 3.239.76.17:80 check
        server 380-web-02 18.206.92.113:80 check
"
echo "$server_config" >> /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
