#!/usr/bin/env bash
#    Creates the file /var/run/myscript.pid containing its PID
#    Displays To infinity and beyond indefinitely
#    Displays I hate the kill command when receiving a SIGTERM signal
#    Displays Y U no love me?! when receiving a SIGINT signal
#    Deletes the file /var/run/myscript.pid and terminates itself when
#    receiving a SIGQUIT or SIGTERM signal

file=$(/var/run/myscript.pid)

while true; do
        echo "To infinity and beyond"
        trap 'echo "I hate the kill command"' SIGTERM
        trap 'echo "Y u no love me?!"' SIGINT
        trap 'rm -f "$file"' SIGQUIT
        trap 'rm -f "$file"' SIGTERM
done

exit 0
