#!/usr/bin/env bash
#    Creates the file /var/run/myscript.pid containing its PID
#    Displays To infinity and beyond indefinitely
#    Displays I hate the kill command when receiving a SIGTERM signal
#    Displays Y U no love me?! when receiving a SIGINT signal
#    Deletes the file /var/run/myscript.pid and terminates itself when
#    receiving a SIGQUIT or SIGTERM signal

echo "$$" > /var/run/holbertonscript.pid

del_file(){
    rm /var/run/myscript.pid
    exit
}
while true
do
        echo "To infinity and beyond"
        trap 'echo "I hate the kill command" -a del_file' SIGTERM
        trap 'echo "Y u no love me?!"' SIGINT
        trap 'del_file' SIGQUIT
done
