#!/usr/bin/env bash
# Displays Best School 10 times but for the 9th iteration, displays
#+ Best School and then Hi on a new line

h=0;

while [ $h -lt 10 ]; do
        echo "Best School"
        (( h++ ))
        if [ $h -eq 9 ]
        then
                echo "Hi"
        fi
done

exit 0
