#!/usr/bin/env bash
# loops from 1 to 10 and:
#+ displays bad luck for the 4th loop iteration
#+ displays good luck for the 8th loop iteration
#+ displays Best School for the other iterations

k=1;

while [ $k -le 10 ]; do
        if [ $k -eq 4 ]
        then
                echo "bad luck"
        elif [ $k -eq 8 ]
        then
                echo "good luck"
        else
                echo "Best School"
        fi

        (( k++ ))
done

exit 0