#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
#+      -displalys hours from 0 to 12
#       -displays minutes from 1 to 59 for each hour

hr=0;

while [ $hr -le 12 ]; do
        echo "Hour: $hr"
        (( hr++ ))
        min=1;
        while [ $min -le 59 ]; do
                echo "$min"
                min=$(( min + 1 ))
        done
done

exit 0
