#!/usr/bin/env bash
# fixing container so that Nginx is running as nginx user
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
pkill apache2
sudo service nginx reload
sudo service nginx restart
