#!/usr/bin/env bash
# fix container to run Nginx as nginx user
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
